"""Configuration values for the vision pipeline."""

WIDTH = 640
HEIGHT = 480
FRAME_FORMAT = "RGB888"

CANNY_LOW = 80
CANNY_HIGH = 160
BLUR_KERNEL = (5, 5)

CIRCLE_BINARY_THRESHOLD = 90
CIRCLE_MIN_AREA = 150
CIRCLE_MAX_AREA = 50000
CIRCLE_MIN_CIRCULARITY = 0.7
CIRCLE_MIN_RADIUS = 8

SAVE_OUTPUT = False
OUTPUT_DIR = "outputs"
SAVE_INTERVAL = 30

STREAM_HOST = "0.0.0.0"
STREAM_PORT = 5000
JPEG_QUALITY = 80

DETECTION_LOG_LIMIT = 50
